#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: cf-uaa-db-password
spec: {}
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: SecretExport
metadata:
  name: cf-uaa-db-password
spec:
  toNamespace: cf-db
